att/rcloud.rcap

app/DESCRIPTION, app/R/controlTypes.R, app/R/dataTableControl.R, app/R/utils.R, app/inst/www/js/ui/controls/dataTable.js, app/tests/testthat/test-generate-table-css.R, app/tests/testthat/test-generate-table-ids-df.R
Background color and text color, towards #99
=> Data Table column colors

inst/www/js/ui/controls/dataTable.js, inst/www/js/ui/controls/gridControl.js, inst/www/js/ui/controls/htmlWidget.js, inst/www/js/ui/controls/iframe.js, inst/www/js/ui/controls/image.js, inst/www/js/ui/controls/interactivePlot.js, inst/www/js/ui/controls/leaflet.js, inst/www/js/ui/controls/pageMenu.js, inst/www/js/ui/controls/rPlot.js, inst/www/js/ui/controls/rPrint.js, inst/www/js/ui/controls/rText.js, inst/www/js/ui/controls/text.js
I haven't reduced it to 1x1. That causes usability issues when interacting with the control.
=> This reduces size of newly added controls

inst/www/js/ui/gridManager.js, inst/www/js/utils/request.js, inst/www/js/viewer.js
This PR allows the width and alignment (left or center) of the canvas from the query string.
> /rcap.html?notebook=29ac441c0e48a9cdccc6d954505b85d3&width=800&align=left
=> Set canvas width and alignment from query string

inst/www/js/ui/controls/child/templates/multiSelect.tpl, inst/www/js/ui/controls/form.js
This PR resolves #136, where multiselect controls would not update correctly where their update contained multiple values.
=> Multiple value update now sets multiselect correctly

inst/www/js/ui/gridManager.js
this fixes #155, whereby the 'no items' message is not shown under some cirucmstances.
=> no items message is shown appropriately

inst/www/styles/default.css, inst/www/styles/default.scss
=> Firefox: controls menu now shown in two column layout

inst/www/js/designer.js, inst/www/js/ui/menuManager.js, inst/www/partials/designer.htm
Promoted from the settings -> Launch Style Editor button to its own main nav button.
=> Style Editor has its own main nav button

inst/www/js/site/pubSubTable.js, inst/www/js/site/site.js, inst/www/js/site/siteManager.js, inst/www/js/ui/dialogManager.js, inst/www/js/ui/dirtyStateIndicator.js, inst/www/partials/designer.htm, inst/www/partials/dialogs/_siteSettings.htm
Adds an empty 'settings' dialog, activated from the main nav's 'settings' icon.
Passes messages around, sets the dirty flag when settings are saved, and creates empty settings object.
=> Site settings dialog and JSON

inst/javascript/rcloud.rcap.js, inst/www/js/site/pubSubTable.js, inst/www/js/site/siteSettings.js, inst/www/js/ui/dialogManager.js, inst/www/js/ui/themeManager.js
Front-end support for RCAP Themes. Configure in the site settings, value is saved/loaded to/from JSON.
=> RCAP Theme Packages

inst/bower.json, inst/www/js/ui/properties/templates/colorControl.tpl, inst/www/styles/default.css, inst/www/styles/spectrum/spectrum.scss
=> Color names for color selection

inst/www/js/ui/controls/child/templates/checkboxList.tpl, inst/www/js/ui/controls/child/templates/radioButtonGroup.tpl, inst/www/js/ui/controls/form.js, inst/www/js/ui/properties/templates/radioButtonGroup.tpl, inst/www/styles/default.css, inst/www/styles/default.scss
This fixes #186 where run time generated radio buttons were differently styled to manually specified radio buttons.
I've simplified the markup, tidied the templates and added some styling that vertically aligns radio buttons/checkboxes with their labels.
=> Consistent radio buttons 

inst/www/js/designer.js, inst/www/js/serializer.js, inst/www/js/site/pubSubTable.js, inst/www/js/site/site.js, inst/www/js/site/siteManager.js, inst/www/js/ui/dialogManager.js, inst/www/js/ui/dirtyStateIndicator.js, inst/www/js/ui/menuManager.js, inst/www/js/ui/pageTreeManager.js, inst/www/js/ui/templates/pageMenuItem.tpl, inst/www/partials/designer.htm, inst/www/styles/default.css, inst/www/styles/default.scss
This fixes #42 and, found whilst implementing drag and drop, #212 too.
RCAP now supports drag and drop for page reordering.
=> Drag and drop for page reordering

inst/www/js/ui/controls/child/dateRange.js, inst/www/js/ui/controls/child/dropdown.js, inst/www/js/ui/controls/child/templates/dropdown.tpl, inst/www/js/ui/controls/form.js, inst/www/js/ui/properties/dropdownProperty.js, inst/www/js/ui/properties/templates/dropdownControl.tpl, inst/www/js/ui/templates/selectOptions.tpl, inst/www/styles/default.css, inst/www/styles/default.scss
Configurable in the designer, using the new 'selection style' value (set to 'dialog') allows the viewer user to select an option value using a dialog.
When the select is clicked, the options are shown in a dialog. If the user selects a value that is different to the currently selected value, a change is triggered (as if the user changed the select value directly).
=> Drop down options can now be selected using an optional dialog

DESCRIPTION, R/controlTypes.R, R/controllerR6.R, R/profileVariableR6.R, R/rcap.result.R, R/rcap.user.profile.R, R/zzz.R, inst/javascript/rcloud.rcap.js, inst/www/js/site/siteManager.js
window.RCAP.getVariables now returns list of variables defined in the design's profile/variables section. 
TODO: we should rename it to getProfileVariables, I left it for now as it was not to break code that you are working on.
There is a set of functions exposed that manage the profile variables values:
* getUserProfileValue
* setUserProfileValue
* deleteUserProfileValue
All new functions return promisses. We should refactor other functions exposed on window.RCAP to return promisses as well.
NOTE:
getVariable function in designer mode will always return an empty list, this is because in the design mode R does NOT parse JSON.
=> Initial implementation of profiled variables.

inst/www/js/ui/controls/form.js, inst/www/js/ui/properties/templates/colorControl.tpl
=> Color pickers work on designer form config

inst/www/js/ui/dialogManager.js
=> Page settings dialog can now be displayed

inst/www/js/ui/properties/templates/colorControl.tpl
=> Can enter color in color dialog

inst/www/js/ui/controls/child/textField.js, inst/www/js/ui/controls/form.js
This fixes #184 by introducing an event handler for the enter key (keyCode 13) which either submits the form or submits the change (which respects the default behaviour of submit button present/not present).
=> Text input enter keydown doesn't redirect

inst/www/js/ui/controls/child/templates/textField.tpl, inst/www/js/ui/controls/child/textField.js, inst/www/styles/default.css, inst/www/styles/default.scss
=> Can specify a width for text fields

inst/www/js/site/pubSubTable.js, inst/www/js/site/site.js, inst/www/js/site/siteManager.js, inst/www/js/ui/controls/baseControl.js, inst/www/js/ui/controls/gridControl.js, inst/www/js/ui/dialogManager.js, inst/www/js/ui/dirtyStateIndicator.js, inst/www/partials/designer.htm, inst/www/partials/dialogs/_executionOrderDialog.htm, inst/www/partials/dialogs/templates/executionOrderDetails.tpl, inst/www/styles/default.css, inst/www/styles/default.scss
=> Execution order

inst/www/js/ui/controls/dataTable.js, inst/www/js/utils/translators/sparklinesTranslator.js
When page changes, redraw dataTables with undrawn sparkgraphs, FIX #292
=> Redraw dataTable on page change

R/rcap.upload.data.R, R/zzz.R, inst/javascript/rcloud.rcap.js
Also allow control over uploaded file permissions, #FIX 294
=> Expose upload for anonymous sessions
