.Rbuildignore
cleanup
install.sh

For the new organization. Instead of the `grunt` call, you'll need to run `./install.sh`. 
To update the bower and npm packages (if you change them, or first time) you need:
```sh
( cd inst && 
npm install && 
bower install && 
cd bower_components/jquery.sparkline && make )
```
@shaneporter @NattyE Please try and let me know if it works for you.

Install script

---

inst/www/js/ui/dirtyStateIndicator.js

This resolves an issue where the dirty state was not always set correctly. Specifically, it was related to control updates. A previous commit introduced the bug.

Dirty state set correctly

---

cleanup
inst/package.json

This PR allows `rcloud.rcap` to be built automatically from the GH repo. It only requires `npm` and `sass` - both are checked for by the build script to give reasonable error messages. All other pieces are installed locally without any system requirements.

fix the build script so it works unattended and uses consistent build tools

---

inst/www/js/ui/controls/dataTable.js

This fixes issue #145. Column names escaped in accordance to datatables rules for '.' column names.
Also gave the the code some more room to breathe. BecauseIliketousewhitespace.

Datatable: can now contain '.' in column names

---

inst/www/js/ui/gridManager.js

Looks as though I'd accidentally pushed something regarding individual page styling.
The grid manager's subscription to 'updatePage', published when the page details are changed, was expecting to find a `styleProperties` property.

Modifying page details doesn't thrown an error

---

inst/www/js/ui/controls/pageMenu.js
inst/www/js/ui/dialogManager.js
inst/www/js/ui/dirtyStateIndicator.js

This fixes #165, where the page menu was prematurely setting the dirty state indicator's modified state.
I also noticed that changing the page menu's style (mobile, vertical, horizontal etc.) would not update the modified state properly. That's been fixed with c6779cf.

Page menu set's dirty flag accordingly

---

R/dataTableControl.R

Fixed thanks to the input of @NattyE

Sparkline options are using histogram counts instead of raw data

---

inst/www/js/assetManager.js
inst/www/js/site/siteManager.js
inst/www/js/ui/themeManager.js

This fixes issue #181, but also ensures that a predictable ordering of CSS assets are used.
That order is package, asset.
So asset (`rcap_designer.css`) can be used to override theme CSS.

Fixes #181 asset/theme CSS issue

---

inst/www/js/ui/controls/child/templates/slider.tpl
inst/www/js/ui/controls/form.js

Prior to this change, every change on a slider resulted in the submission of data; if that submission's resulting code took a while to execute, the user would be left frustrated, waiting for every iteration to execute. Really, only the 'final' change would be required.
This PR tackles this issue. The slider now hooks up the 'finish' event rather than 'change'.

Auto-submitting slider doesn't submit for every change

---

inst/javascript/rcloud.rcap.js

Can't write to the `rcap_designer.json` asset for read-only notebooks, so this PR prevents (albeit with some inelegant UI) RCAP's usage for read-only notebooks.

Prevent RCAP's usage for read-only notebooks

---

inst/www/js/ui/pageTreeManager.js

Try as I might to fix this using the 'updateNode' method, I could not. I tried, using a simple use case, to create a working example and add code to break it. It never worked.
Ultimately, I modify the html of the tree element; although not my preferred solution, after spending a while to resolve this issue, it is time to move onto something else.

Renamed pages are not (UI) removed from the tree

---

inst/www/js/ui/gridManager.js

Viewer grid height was being set to 48 in all cases. Whilst this provides sufficient space for designer dashboard construction, it resulted whitespace at the bottom of pages in the viewer.
This PR calculates the height that's required by looping through each page's controls and keeping a max value for the controls' y + height.

Excessive whitespace trimmed from bottom of viewer pages

---

R/controlR6.R
R/controllerR6.R
R/rcap.result.R
R/zzz.R
inst/javascript/rcloud.rcap.js

To perform update of the profile variable control invoke something like this to set the variable
var updateVarsJSON = JSON.stringify({
updatedVariables:[{
variableName: "myCountriesVariable",
controlId: "8b934572effe3",
value: ["Netherlands", "Luxemburg"]
}]
});
window.RCAP.updateControls(updateVarsJSON);
or to unset the variable
var updateVarsJSON = JSON.stringify({
updatedVariables:[{
variableName: "myCountriesVariable",
controlId: "8b934572effe3",
value: []
}]
});
window.RCAP.updateControls(updateVarsJSON);
to fetch available values for given profile variable invoke:
window.RCAP.getUserProfileVariableValues(variableName)
to get current user profile variable value invoke:
window.RCAP.getUserProfileValue(variableName)
Both always return an array of objects

Expose functions for managing profile variables in view mode

---

R/controlTypes.R
R/rcap.user.profile.R
R/zzz.R
inst/javascript/rcloud.rcap.js

The returned types of functions that are used by Profile Settings dialog haven't changed so this should just work.
Tested it with our two test dashboards and both work fine.

Switch from redis to HTML5 localStorage

---

inst/www/js/ui/menuManager.js

This fixes #247, where opened menus would stay open when RCAP was reopened.
This hides them.

Menus closed when RCAP quits

---

inst/www/js/ui/pageTreeManager.js

This issue was introduced when jqTree was used for the 'page tree'. The line of code to select the newly created page had been commented out, because it used an invalid selector.
This PR uses the better `changedSelectedPageId` event to update the grid.

Designer switches to newly created page automatically

---

inst/www/js/pages/page.js

The duplication process _intended_ to change the page and control IDs, but this was not working properly, and the duplication of IDs caused issues with non-updating plots and page menus not working. With the duplication issue apparent, it's not difficult to understand why.

Duplicating pages fixed

---

inst/www/js/pages/page.js
inst/www/js/ui/gridManager.js

Control IDs were not being changed in the `duplicate` method and moreover, the code that added the grid was taking the source page's details and overwriting those of the new page because of a selector issue.
This doesn't, as I thought, fix #258.

Duplicate page's controls are independent

---

inst/www/js/designer.js
inst/www/js/pages/page.js
inst/www/js/ui/controls/breadcrumb.js
inst/www/js/ui/controls/factories/controlFactory.js
inst/www/js/ui/dialogManager.js
inst/www/js/ui/menuManager.js
inst/www/js/ui/messageManager.js
inst/www/js/ui/pageTreeManager.js

`ControlFactory` `duplciateControl` method solves the issue.
The duplication code was superficially ok, but didn't hook up events that the breadcrumb need to react to.

Breadcrumb control update automatically on page duplicate

---

R/controlTypes.R
R/zzz.R
inst/www/js/ui/viewerDialogManager.js

Increase file limit to 500MB
Format file sizes so units are displayed
Fix download progress spinner, so it appears when file is downloaded, not after.

Fix date/time format of files last modification times

---

R/dataTableControl.R
inst/www/js/utils/translators/sparklinesTranslator.js

Also allow dashboard designers to override the default height (and other sparkline options) from notebook, FIX #192

Set height of sparkline graphs
